CREATE TABLE "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "price_int" integer NOT NULL,
  "price_dec" integer DEFAULT 0,
  "label_id" integer DEFAULT null,
  "images" varchar[] DEFAULT null,
  "description" text DEFAULT null,
  "in_stock" bool NOT NULL
);

CREATE TABLE "labels" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "slug" varchar UNIQUE NOT NULL,
  "img_url" varchar DEFAULT NULL
);

CREATE TABLE "product_categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer NOT NULL,
  "category_id" integer NOT NULL
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "is_admin" bool DEFAULT false,
  "password" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "comments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "text" text NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "product_count" integer NOT NULL,
  "price_int" integer NOT NULL,
  "price_dec" integer DEFAULT 0,
  "delivery_price_int" integer NOT NULL,
  "delivery_price_dec" integer DEFAULT 0,
  "total_int" integer NOT NULL,
  "total_dec" integer DEFAULT 0,
  "country_id" integer NOT NULL,
  "district" varchar NOT NULL,
  "city" varchar NOT NULL,
  "postal_code" integer NOT NULL,
  "delivery_method_id" integer NOT NULL,
  "payment_method_id" integer NOT NULL,
  "customer_firstname" varchar NOT NULL,
  "cusotmer_middlename" varchar NOT NULL,
  "customer_lastname" varchar NOT NULL,
  "customer_phone_number" varchar NOT NULL,
  "customer_email" varchar NOT NULL,
  "customer_address" text NOT NULL,
  "customer_comment" text DEFAULT null,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "product_orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer NOT NULL,
  "order_id" integer NOT NULL,
  "count" integer NOT NULL
);

CREATE TABLE "countries" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "delivery_methods" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "payment_methods" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "shopping_session" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "total_int" integer DEFAULT 0,
  "total_dec" integer DEFAULT 0
);

CREATE TABLE "cart_item" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_id" integer NOT NULL,
  "product_id" integer NOT NULL,
  "quantity" integer NOT NULL
);

COMMENT ON COLUMN "users"."password" IS 'hashed version';

ALTER TABLE "products" ADD FOREIGN KEY ("label_id") REFERENCES "labels" ("id");

ALTER TABLE "product_categories" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "product_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("country_id") REFERENCES "countries" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("delivery_method_id") REFERENCES "delivery_methods" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("payment_method_id") REFERENCES "payment_methods" ("id");

ALTER TABLE "product_orders" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "product_orders" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "shopping_session" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "cart_item" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "cart_item" ADD FOREIGN KEY ("session_id") REFERENCES "shopping_session" ("id") ON DELETE CASCADE;

INSERT INTO categories (name, slug, img_url) VALUES ('Клавишные инструменты', 'keyboards', '/assets/images/categories/keyboards.jpg');
INSERT INTO categories (name, slug, img_url) VALUES ('Гитары', 'guitars', '/assets/images/categories/guitars.jpg');
INSERT INTO categories (name, slug, img_url) VALUES ('Духовые инструменты', 'wind-instruments', '/assets/images/categories/wind-instruments.jpg');
INSERT INTO categories (name, slug, img_url) VALUES ('Ударные инструменты', 'percussion', '/assets/images/categories/percussion.jpg');
INSERT INTO categories (name, slug, img_url) VALUES ('Звуковое оборудование', 'sound-equipment', '/assets/images/categories/sound-equipment.jpg');
INSERT INTO categories (name, slug, img_url) VALUES ('Микрофоны', 'mics', '/assets/images/categories/mics.jpg');
INSERT INTO categories (name, slug, img_url) VALUES ('Разъемы и кабели', 'cables', '/assets/images/categories/cables.jpg');

insert into labels (name) values ('Honor');
insert into labels (name) values ('Huawey');
insert into labels (name) values ('LG');

insert into products (name, price_int, label_id, images, description, in_stock) values ('Alhambra', '1200', '1','{ "/assets/images/products/alhambra.jpg", "/assets/images/products/alhambra_1.jpg", "/assets/images/products/alhambra_2.jpg" }'::varchar[], 'cool guitar', true);
insert into products (name, price_int, label_id, images, description, in_stock) values ('ALMANSA', '900', '2','{ "/assets/images/products/almansa.jpg", "/assets/images/products/almansa_1.jpg", "/assets/images/products/almansa_2.jpg", "/assets/images/products/almansa_3.jpg", "/assets/images/products/almansa_4.jpg", "/assets/images/products/almansa_5.jpg", "/assets/images/products/almansa_6.jpg" }'::varchar[], 'ALMANSA 402 Cedro – 6-струнная полноразмерная классическая гитара.
Модель из серии гитар (Estudio). Верхняя дека из массива кедра, корпус из слоеного красного дерева, гриф из красного дерева с накладкой из индийского палисандра. Мензура 650 мм, ширина верхнего порожка 52 мм. Глянцевая отделка.
Произведена в Испании.', true);
insert into product_categories (product_id, category_id) values ('1', '2');
insert into product_categories (product_id, category_id) values ('2', '2');

insert into products (name, price_int, label_id, description, in_stock) values ('KAWAI CR-40 TRANSPARENCY', '4000', '3', 'cool piano', true);
insert into product_categories (product_id, category_id) values ('3', '1');

insert into countries (name) values ('Россия');
insert into countries (name) values ('Беларусь');
insert into countries (name) values ('Украина');
insert into countries (name) values ('Казахстан');

insert into delivery_methods (name) values ('ТК Деловые линии');
insert into delivery_methods (name) values ('ТК СДЕК');
insert into delivery_methods (name) values ('Курьером');
insert into delivery_methods (name) values ('Самовывоз');

insert into payment_methods (name) values ('Банковской картой');
insert into payment_methods (name) values ('Наличные');

-- pass: admin
INSERT INTO users (username, email, is_admin, password) VALUES ('admin', 'admin@admin.ru', 'true', '$2a$10$DS/dEObNUtdY4Q6LCdbSf.FjRE3y87tB0pC9bwSaiVADQK5tGoHEm');
-- pass: user
INSERT INTO users (username, email, is_admin, password) VALUES ('user', 'user@user.com', 'false', '$2a$10$Rx6oImAgXCqrlKlz1nRNlOnLLPtVDksvevkmMazB0XCMGkcJWHHTi');
