// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: cart_item.sql

package db

import (
	"context"
)

const createCartItem = `-- name: CreateCartItem :one
insert into cart_item (
  session_id,
  product_id,
  quantity
)  values (
  $1, $2, $3
) returning id, session_id, product_id, quantity
`

type CreateCartItemParams struct {
	SessionID int32 `json:"session_id"`
	ProductID int32 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
}

func (q *Queries) CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, createCartItem, arg.SessionID, arg.ProductID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ProductID,
		&i.Quantity,
	)
	return i, err
}
