// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: delivery_methods.sql

package db

import (
	"context"
)

const listDeliveryMethods = `-- name: ListDeliveryMethods :many
select id, name from delivery_methods
limit $1
offset $2
`

type ListDeliveryMethodsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDeliveryMethods(ctx context.Context, arg ListDeliveryMethodsParams) ([]DeliveryMethod, error) {
	rows, err := q.db.QueryContext(ctx, listDeliveryMethods, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryMethod
	for rows.Next() {
		var i DeliveryMethod
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
