// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: labels.sql

package db

import (
	"context"
)

const listLabels = `-- name: ListLabels :many
select id, name from labels
order by id
limit $1
offset $2
`

type ListLabelsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLabels(ctx context.Context, arg ListLabelsParams) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listLabels, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
