// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Category struct {
	ID   int32
	Name string
}

type Comment struct {
	ID        int32
	UserID    int32
	Text      string
	CreatedAt sql.NullTime
}

type Country struct {
	ID   int32
	Name sql.NullString
}

type DeliveryMethod struct {
	ID   int32
	Name sql.NullString
}

type Lable struct {
	ID   int32
	Name string
}

type Order struct {
	ID                  int32
	UserID              sql.NullInt32
	ProductCount        int32
	PriceInt            int32
	PriceDec            sql.NullInt32
	DeliveryPriceInt    int32
	DeliveryPriceDec    sql.NullInt32
	TotalInt            int32
	TotalDec            sql.NullInt32
	CountryID           sql.NullInt32
	District            string
	City                string
	PostalCode          int32
	DeliveryMethodID    int32
	PaymentMethodID     int32
	CustomerFirstname   string
	CusotmerMiddlename  string
	CustomerLastname    string
	CustomerPhoneNumber string
	CustomerEmail       string
	CustomerAddress     string
	CustomerComment     sql.NullString
	CreatedAt           sql.NullTime
}

type PaymentMethod struct {
	ID   int32
	Name sql.NullString
}

type Product struct {
	ID          int32
	Name        string
	PriceInt    int32
	PriceDec    sql.NullInt32
	LabelID     sql.NullInt32
	ImgUrl      sql.NullString
	Description sql.NullString
	InStock     sql.NullBool
}

type ProductCategory struct {
	ID         int32
	ProductID  int32
	CategoryID int32
}

type ProductOrder struct {
	ID        int32
	ProductID int32
	OrderID   int32
	Count     int32
}

type User struct {
	ID       int32
	Username string
	Email    string
	IsAdmin  sql.NullBool
	// hashed version
	Password  string
	CreatedAt sql.NullTime
}
