// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: products.sql

package db

import (
	"context"
)

const getProduct = `-- name: GetProduct :one
SELECT id, name, price_int, price_dec, label_id, img_url, description, in_stock FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInt,
		&i.PriceDec,
		&i.LabelID,
		&i.ImgUrl,
		&i.Description,
		&i.InStock,
	)
	return i, err
}

const getProductsByCategory = `-- name: GetProductsByCategory :many
SELECT p.id, p.name, p.price_int, p.price_dec, p.label_id, p.img_url, p.description, p.in_stock FROM products p, product_categories p_c
WHERE p.id = p_c.product_id
  AND $1 = p_c.category_id 
  AND (CASE WHEN $2::integer > 0 THEN p.price_int >= $2 ELSE p.price_int > 0 END)
  AND (CASE WHEN $3::integer > 0 THEN p.price_int <= $3 ELSE p.price_int < 999999 END)
  AND (CASE WHEN $4::integer > 0 THEN p.label_id = $4 ELSE TRUE END)
ORDER BY 
CASE WHEN $5::varchar(10) = 'ASC' THEN p.price_int END asc,
CASE WHEN $5::varchar(10) = 'DESC' THEN p.price_int END desc
`

type GetProductsByCategoryParams struct {
	CategoryID   int32  `json:"category_id"`
	MinPrice     int32  `json:"min_price"`
	MaxPrice     int32  `json:"max_price"`
	LabelID      int32  `json:"label_id"`
	PriceSorting string `json:"price_sorting"`
}

func (q *Queries) GetProductsByCategory(ctx context.Context, arg GetProductsByCategoryParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getProductsByCategory,
		arg.CategoryID,
		arg.MinPrice,
		arg.MaxPrice,
		arg.LabelID,
		arg.PriceSorting,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInt,
			&i.PriceDec,
			&i.LabelID,
			&i.ImgUrl,
			&i.Description,
			&i.InStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
